INSERT INTO FIT5042.CONTACT_PERSON (CONTACT_PERSON_ID, "NAME", PHONE_NUMBER)
	VALUES (1, 'Eddie Leung', '0411234567');
INSERT INTO FIT5042.CONTACT_PERSON (CONTACT_PERSON_ID, "NAME", PHONE_NUMBER) 
	VALUES (2, 'Jennifer Huang', '0422334335'); 
INSERT INTO FIT5042.CONTACT_PERSON (CONTACT_PERSON_ID, "NAME", PHONE_NUMBER) 
	VALUES (3, 'Luke Steller', '0409233432');


INSERT INTO FIT5042.PROPERTY (PROPERTY_ID, NUMBER_OF_BEDROOMS, PRICE, "SIZE", POSTCODE, "STATE", STREET_ADDRESS, STREET_NUMBER, SUBURB, CONTACTPERSON_CONTACT_PERSON_ID) 
	VALUES (1, 2, 250000, 150, '3145', 'Victoria', 'Boston Avenue', '24', 'Malvern East', 1);
INSERT INTO FIT5042.PROPERTY (PROPERTY_ID, NUMBER_OF_BEDROOMS, PRICE, "SIZE", POSTCODE, "STATE", STREET_ADDRESS, STREET_NUMBER, SUBURB, CONTACTPERSON_CONTACT_PERSON_ID) 
	VALUES (2, 4, 425000, 360, '3168', 'Victoria', 'Bettina Street', '11', 'Clayton', 1);
INSERT INTO FIT5042.PROPERTY (PROPERTY_ID, NUMBER_OF_BEDROOMS, PRICE, "SIZE", POSTCODE, "STATE", STREET_ADDRESS, STREET_NUMBER, SUBURB, CONTACTPERSON_CONTACT_PERSON_ID) 
	VALUES (3, 3, 600000, 150, '3163', 'Victoria', 'Wattle Avenue', '3', 'Glen Huntly', 2);
INSERT INTO FIT5042.PROPERTY (PROPERTY_ID, NUMBER_OF_BEDROOMS, PRICE, "SIZE", POSTCODE, "STATE", STREET_ADDRESS, STREET_NUMBER, SUBURB, CONTACTPERSON_CONTACT_PERSON_ID) 
	VALUES (4, 5, 553000, 150, '3204', 'Victoria', 'Hamilton Street', '5', 'Bentleigh', 3);